### Пример 1

Моделируем 60-ти кратное подбрасование игральной кости. 
Событием А будем считать выыподение числа 3 
и найдем его относительною частоту

In [2]:
import numpy as np
np.random.seed(1)
n = 60
b = np.random.randint(1, 7, n)
b

array([6, 4, 5, 1, 2, 4, 6, 1, 1, 2, 5, 6, 5, 2, 3, 5, 6, 3, 5, 4, 5, 3,
       5, 6, 3, 5, 2, 2, 1, 6, 2, 2, 6, 2, 2, 1, 5, 2, 1, 1, 6, 4, 3, 2,
       1, 4, 6, 2, 2, 4, 5, 1, 2, 4, 5, 3, 5, 1, 6, 4])

Вычислим мощность подможества, где в результате испытания  
выпадало число 3, то есть наблюдалось событие А

In [3]:
a=b[b==3]
a

array([3, 3, 3, 3, 3, 3])

In [4]:
m = len(a)
m

6

Вычисляем относительною частоту события А

In [5]:
M = m / n
M

0.1

### Пример 2

Моделируем ситуацию: Бросаем две игральные кости одновременно.
При этом будем находить частоту случайного события B, при котором на одной кости выпало 1, а на другой - 2.
Проведем для этого 360 испытоний. 

In [6]:
n = 360 
c = np.random.randint(1, 7, n)
d = np.random.randint(1, 7, n)

Посчитаем число случаев, когда в одном испытании на первой 
игральной кости выпало число 1, а на второй - 2.

In [7]:
a = c[(c==1) & (d==2)]
m = len(a)
a, m

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 11)

Вычислим относительную частоту события B

In [8]:
W = m / n
W

0.030555555555555555

## Комбинаторика

### Пример 1
Сколькими способами можно выбрать из колоды, состоящий из 36 карт, 4 карты?

In [9]:
from math import factorial

In [10]:
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))

In [11]:
combinations(36, 4)

58905

### Пример 2
В магазине 20 покупателей. Сколькими способами они могут образовать очередь из 5 человек?

In [12]:
def arrangements(n, k):
    return int(factorial(n) / factorial(n -k))

In [13]:
arrangements(20, 5)

1860480

### Пример 3
Скольким способами 5 покупателей могут образовать очередь

In [14]:
def permutations(n):
    return int(factorial(n))

In [15]:
permutations(5)

120

### Пример 4
Из колоды, состоящей из 36 карт случайным образом выбраны 5. Сколькими способами можно выбрать эти карты так, чтобы среди них оказалось от 2 до 3 Тузов 

In [16]:
# Количество комбинаций только Тузов. С 2 -тузами и с 3 -тузами отдельно
C_1_t = combinations(4, 2)
C_2_t = combinations(4, 3)
C_1_t, C_2_t

(6, 4)

In [17]:
# Количество комбинаций без Тузов. С 2 -тузами и с 3 -тузами отдельно
C_1_n = combinations(32, 3)
C_2_n = combinations(32, 2)
C_1_n, C_2_n

(4960, 496)

In [18]:
# Количество комбинаций . С 2 -тузами и с 3 -тузами отдельно
C_1 = C_1_t * C_1_n
C_2 = C_2_t * C_2_n
C_1, C_2

(29760, 1984)

In [19]:
# Всего комбинаций 
C = C_1 + C_2
print(f' ОТВЕТ: Всего возможно {C} - комбинаций')

 ОТВЕТ: Всего возможно 31744 - комбинаций


### Пример 5
Из колоды 36 карт случайным образом берут 5 карт.
Найти вероятность того, среди 5 карт будет 2 туза

In [21]:
# Находим количество нужных исходов
C_1_t = combinations(4, 2)
C_1_n = combinations(32, 3)
C_1 = C_1_t * C_1_n
C_1

29760

In [37]:
# Находим общее число исходов 
C = combinations(36, 5)
C

376992

In [48]:
# Находим вероятность того, среди 5 карт будет 2 туза
P = C_1 / C
print(f'ОТВЕТ: Вероятность того, что среди 5 карт, взятых из колоды в 36, \
будет 2 туза - {round(P, 4)} или около {round(P*100)} %')

ОТВЕТ: Вероятность того, что среди 5 карт, взятых из колоды в 36, будет 2 туза - 0.0789 или около 8 %


### Пример 6
